package mc.mod;

import java.util.List;

/**
 * Minecraft's and NeoForge's tags, limited to the blocks and items reamc has (generated from the game's tag
 * files; mods add to these with their own tag files).
 */
final class VanillaTags {
    private VanillaTags() { }

    interface Sink { void add(String registry, String tag, List<String> entries, boolean replace); }

    static void addTo(Sink s) {
        s.add("block", "c:bookshelves", ids("bookshelf"), false);
        s.add("block", "c:chests", ids("chest"), false);
        s.add("block", "c:chests/wooden", ids("chest"), false);
        s.add("block", "c:cobblestones", ids("cobblestone", "mossy_cobblestone"), false);
        s.add("block", "c:cobblestones/mossy", ids("mossy_cobblestone"), false);
        s.add("block", "c:cobblestones/normal", ids("cobblestone"), false);
        s.add("block", "c:dyed", ids("black_carpet", "black_wool", "blue_carpet", "blue_wool", "green_carpet", "green_wool", "red_bed", "red_carpet", "red_wool", "white_carpet", "white_wool", "yellow_carpet", "yellow_wool"), false);
        s.add("block", "c:dyed/black", ids("black_carpet", "black_wool"), false);
        s.add("block", "c:dyed/blue", ids("blue_carpet", "blue_wool"), false);
        s.add("block", "c:dyed/green", ids("green_carpet", "green_wool"), false);
        s.add("block", "c:dyed/red", ids("red_bed", "red_carpet", "red_wool"), false);
        s.add("block", "c:dyed/white", ids("white_carpet", "white_wool"), false);
        s.add("block", "c:dyed/yellow", ids("yellow_carpet", "yellow_wool"), false);
        s.add("block", "c:fence_gates", ids("oak_fence_gate"), false);
        s.add("block", "c:fence_gates/wooden", ids("oak_fence_gate"), false);
        s.add("block", "c:fences", ids("oak_fence"), false);
        s.add("block", "c:fences/wooden", ids("oak_fence"), false);
        s.add("block", "c:glass_blocks", ids("glass"), false);
        s.add("block", "c:glass_blocks/cheap", ids("glass"), false);
        s.add("block", "c:glass_blocks/colorless", ids("glass"), false);
        s.add("block", "c:glass_panes", ids("glass_pane"), false);
        s.add("block", "c:glass_panes/colorless", ids("glass_pane"), false);
        s.add("block", "c:gravels", ids("gravel"), false);
        s.add("block", "c:netherracks", ids("netherrack"), false);
        s.add("block", "c:obsidians", ids("obsidian"), false);
        s.add("block", "c:obsidians/normal", ids("obsidian"), false);
        s.add("block", "c:ore_bearing_ground/netherrack", ids("netherrack"), false);
        s.add("block", "c:ore_bearing_ground/stone", ids("stone"), false);
        s.add("block", "c:ore_rates/dense", ids("lapis_ore", "redstone_ore"), false);
        s.add("block", "c:ore_rates/singular", ids("coal_ore", "diamond_ore", "emerald_ore", "gold_ore", "iron_ore", "nether_quartz_ore"), false);
        s.add("block", "c:ores", ids("coal_ore", "diamond_ore", "emerald_ore", "gold_ore", "iron_ore", "lapis_ore", "nether_quartz_ore", "redstone_ore"), false);
        s.add("block", "c:ores/coal", ids("coal_ore"), false);
        s.add("block", "c:ores/diamond", ids("diamond_ore"), false);
        s.add("block", "c:ores/emerald", ids("emerald_ore"), false);
        s.add("block", "c:ores/gold", ids("gold_ore"), false);
        s.add("block", "c:ores/iron", ids("iron_ore"), false);
        s.add("block", "c:ores/lapis", ids("lapis_ore"), false);
        s.add("block", "c:ores/quartz", ids("nether_quartz_ore"), false);
        s.add("block", "c:ores/redstone", ids("redstone_ore"), false);
        s.add("block", "c:ores_in_ground/netherrack", ids("nether_quartz_ore"), false);
        s.add("block", "c:ores_in_ground/stone", ids("coal_ore", "diamond_ore", "emerald_ore", "gold_ore", "iron_ore", "lapis_ore", "redstone_ore"), false);
        s.add("block", "c:player_workstations/crafting_tables", ids("crafting_table"), false);
        s.add("block", "c:player_workstations/furnaces", ids("furnace"), false);
        s.add("block", "c:pumpkins", ids("pumpkin"), false);
        s.add("block", "c:pumpkins/normal", ids("pumpkin"), false);
        s.add("block", "c:sands", ids("sand"), false);
        s.add("block", "c:sands/colorless", ids("sand"), false);
        s.add("block", "c:sandstone/blocks", ids("sandstone"), false);
        s.add("block", "c:sandstone/slabs", ids("sandstone_slab"), false);
        s.add("block", "c:sandstone/stairs", ids("sandstone_stairs"), false);
        s.add("block", "c:sandstone/uncolored_blocks", ids("sandstone"), false);
        s.add("block", "c:sandstone/uncolored_slabs", ids("sandstone_slab"), false);
        s.add("block", "c:sandstone/uncolored_stairs", ids("sandstone_stairs"), false);
        s.add("block", "c:stones", ids("andesite", "diorite", "granite", "stone"), false);
        s.add("block", "c:storage_blocks", ids("diamond_block", "emerald_block", "gold_block", "iron_block", "lapis_block", "redstone_block"), false);
        s.add("block", "c:storage_blocks/diamond", ids("diamond_block"), false);
        s.add("block", "c:storage_blocks/emerald", ids("emerald_block"), false);
        s.add("block", "c:storage_blocks/gold", ids("gold_block"), false);
        s.add("block", "c:storage_blocks/iron", ids("iron_block"), false);
        s.add("block", "c:storage_blocks/lapis", ids("lapis_block"), false);
        s.add("block", "c:storage_blocks/redstone", ids("redstone_block"), false);
        s.add("block", "c:villager_job_sites", ids("brewing_stand"), false);
        s.add("block", "minecraft:animals_spawnable_on", ids("grass_block"), false);
        s.add("block", "minecraft:anvil", ids("anvil"), false);
        s.add("block", "minecraft:armadillo_spawnable_on", ids("coarse_dirt", "grass_block", "terracotta"), false);
        s.add("block", "minecraft:axolotls_spawnable_on", ids("clay"), false);
        s.add("block", "minecraft:azalea_grows_on", ids("coarse_dirt", "dirt", "grass_block", "sand", "snow_block", "terracotta"), false);
        s.add("block", "minecraft:azalea_root_replaceable", ids("andesite", "clay", "coarse_dirt", "diorite", "dirt", "granite", "grass_block", "gravel", "sand", "snow_block", "stone", "terracotta"), false);
        s.add("block", "minecraft:badlands_terracotta", ids("terracotta"), false);
        s.add("block", "minecraft:bamboo_plantable_on", ids("coarse_dirt", "dirt", "grass_block", "gravel", "sand"), false);
        s.add("block", "minecraft:base_stone_nether", ids("netherrack"), false);
        s.add("block", "minecraft:base_stone_overworld", ids("andesite", "diorite", "granite", "stone"), false);
        s.add("block", "minecraft:beacon_base_blocks", ids("diamond_block", "emerald_block", "gold_block", "iron_block"), false);
        s.add("block", "minecraft:beds", ids("red_bed"), false);
        s.add("block", "minecraft:bee_growables", ids("carrots", "potatoes", "wheat"), false);
        s.add("block", "minecraft:big_dripleaf_placeable", ids("clay", "coarse_dirt", "dirt", "farmland", "grass_block"), false);
        s.add("block", "minecraft:birch_logs", ids("birch_log"), false);
        s.add("block", "minecraft:blocks_wind_charge_explosions", ids("bedrock"), false);
        s.add("block", "minecraft:buttons", ids("oak_button", "stone_button"), false);
        s.add("block", "minecraft:camel_sand_step_sound_blocks", ids("sand"), false);
        s.add("block", "minecraft:climbable", ids("ladder"), false);
        s.add("block", "minecraft:coal_ores", ids("coal_ore"), false);
        s.add("block", "minecraft:combination_step_sound_blocks", ids("black_carpet", "blue_carpet", "green_carpet", "red_carpet", "snow", "white_carpet", "yellow_carpet"), false);
        s.add("block", "minecraft:completes_find_tree_tutorial", ids("birch_leaves", "birch_log", "oak_leaves", "oak_log", "spruce_leaves", "spruce_log"), false);
        s.add("block", "minecraft:convertable_to_mud", ids("coarse_dirt", "dirt"), false);
        s.add("block", "minecraft:crops", ids("carrots", "potatoes", "wheat"), false);
        s.add("block", "minecraft:dampens_vibrations", ids("black_carpet", "black_wool", "blue_carpet", "blue_wool", "green_carpet", "green_wool", "red_carpet", "red_wool", "white_carpet", "white_wool", "yellow_carpet", "yellow_wool"), false);
        s.add("block", "minecraft:dead_bush_may_place_on", ids("coarse_dirt", "dirt", "grass_block", "sand", "terracotta"), false);
        s.add("block", "minecraft:diamond_ores", ids("diamond_ore"), false);
        s.add("block", "minecraft:dirt", ids("coarse_dirt", "dirt", "grass_block"), false);
        s.add("block", "minecraft:doors", ids("iron_door", "oak_door"), false);
        s.add("block", "minecraft:dragon_immune", ids("bedrock", "iron_bars", "obsidian"), false);
        s.add("block", "minecraft:dragon_transparent", ids("fire"), false);
        s.add("block", "minecraft:dripstone_replaceable_blocks", ids("andesite", "diorite", "granite", "stone"), false);
        s.add("block", "minecraft:emerald_ores", ids("emerald_ore"), false);
        s.add("block", "minecraft:enchantment_power_provider", ids("bookshelf"), false);
        s.add("block", "minecraft:enchantment_power_transmitter", ids("dead_bush", "fern", "fire", "lava", "short_grass", "snow", "water"), false);
        s.add("block", "minecraft:enderman_holdable", ids("blue_orchid", "brown_mushroom", "cactus", "clay", "coarse_dirt", "dandelion", "dirt", "grass_block", "gravel", "melon", "poppy", "pumpkin", "red_mushroom", "sand", "tnt"), false);
        s.add("block", "minecraft:fall_damage_resetting", ids("ladder"), false);
        s.add("block", "minecraft:features_cannot_replace", ids("bedrock", "chest", "spawner"), false);
        s.add("block", "minecraft:fence_gates", ids("oak_fence_gate"), false);
        s.add("block", "minecraft:fences", ids("oak_fence"), false);
        s.add("block", "minecraft:fire", ids("fire"), false);
        s.add("block", "minecraft:flowers", ids("blue_orchid", "dandelion", "poppy"), false);
        s.add("block", "minecraft:foxes_spawnable_on", ids("coarse_dirt", "grass_block", "snow", "snow_block"), false);
        s.add("block", "minecraft:frogs_spawnable_on", ids("grass_block"), false);
        s.add("block", "minecraft:geode_invalid_blocks", ids("bedrock", "ice", "lava", "water"), false);
        s.add("block", "minecraft:goats_spawnable_on", ids("grass_block", "gravel", "snow", "snow_block", "stone"), false);
        s.add("block", "minecraft:gold_ores", ids("gold_ore"), false);
        s.add("block", "minecraft:guarded_by_piglins", ids("chest", "gold_block", "gold_ore"), false);
        s.add("block", "minecraft:hoglin_repellents", ids("nether_portal"), false);
        s.add("block", "minecraft:ice", ids("ice"), false);
        s.add("block", "minecraft:impermeable", ids("glass"), false);
        s.add("block", "minecraft:incorrect_for_gold_tool", ids("diamond_block", "diamond_ore", "emerald_block", "emerald_ore", "gold_block", "gold_ore", "iron_block", "iron_ore", "lapis_block", "lapis_ore", "obsidian", "redstone_ore"), false);
        s.add("block", "minecraft:incorrect_for_iron_tool", ids("obsidian"), false);
        s.add("block", "minecraft:incorrect_for_stone_tool", ids("diamond_block", "diamond_ore", "emerald_block", "emerald_ore", "gold_block", "gold_ore", "obsidian", "redstone_ore"), false);
        s.add("block", "minecraft:incorrect_for_wooden_tool", ids("diamond_block", "diamond_ore", "emerald_block", "emerald_ore", "gold_block", "gold_ore", "iron_block", "iron_ore", "lapis_block", "lapis_ore", "obsidian", "redstone_ore"), false);
        s.add("block", "minecraft:infiniburn_end", ids("bedrock", "netherrack"), false);
        s.add("block", "minecraft:infiniburn_nether", ids("netherrack"), false);
        s.add("block", "minecraft:infiniburn_overworld", ids("netherrack"), false);
        s.add("block", "minecraft:iron_ores", ids("iron_ore"), false);
        s.add("block", "minecraft:lapis_ores", ids("lapis_ore"), false);
        s.add("block", "minecraft:lava_pool_stone_cannot_replace", ids("bedrock", "birch_leaves", "birch_log", "chest", "oak_leaves", "oak_log", "spawner", "spruce_leaves", "spruce_log"), false);
        s.add("block", "minecraft:leaves", ids("birch_leaves", "oak_leaves", "spruce_leaves"), false);
        s.add("block", "minecraft:logs", ids("birch_log", "oak_log", "spruce_log"), false);
        s.add("block", "minecraft:logs_that_burn", ids("birch_log", "oak_log", "spruce_log"), false);
        s.add("block", "minecraft:lush_ground_replaceable", ids("andesite", "clay", "coarse_dirt", "diorite", "dirt", "granite", "grass_block", "gravel", "sand", "stone"), false);
        s.add("block", "minecraft:maintains_farmland", ids("carrots", "potatoes", "wheat"), false);
        s.add("block", "minecraft:mangrove_roots_can_grow_through", ids("snow"), false);
        s.add("block", "minecraft:mineable/axe", ids("birch_log", "birch_planks", "birch_slab", "birch_stairs", "bookshelf", "brown_mushroom", "carrots", "chest", "crafting_table", "dead_bush", "fern", "ladder", "melon", "nether_wart", "oak_button", "oak_door", "oak_fence", "oak_fence_gate", "oak_log", "oak_planks", "oak_pressure_plate", "oak_sapling", "oak_slab", "oak_stairs", "oak_trapdoor", "potatoes", "pumpkin", "red_mushroom", "short_grass", "spruce_log", "spruce_planks", "spruce_slab", "spruce_stairs", "sugar_cane", "wheat"), false);
        s.add("block", "minecraft:mineable/hoe", ids("birch_leaves", "oak_leaves", "spruce_leaves"), false);
        s.add("block", "minecraft:mineable/pickaxe", ids("andesite", "anvil", "brewing_stand", "brick_slab", "brick_stairs", "bricks", "coal_ore", "cobblestone", "cobblestone_slab", "cobblestone_stairs", "cobblestone_wall", "detector_rail", "diamond_block", "diamond_ore", "diorite", "emerald_block", "emerald_ore", "enchanting_table", "furnace", "gold_block", "gold_ore", "granite", "ice", "iron_bars", "iron_block", "iron_door", "iron_ore", "lapis_block", "lapis_ore", "mossy_cobblestone", "nether_bricks", "nether_quartz_ore", "netherrack", "obsidian", "piston", "piston_head", "powered_rail", "quartz_block", "rail", "redstone_block", "redstone_ore", "sandstone", "sandstone_slab", "sandstone_stairs", "smooth_stone_slab", "spawner", "sticky_piston", "stone", "stone_brick_slab", "stone_brick_stairs", "stone_bricks", "stone_button", "stone_pressure_plate", "terracotta"), false);
        s.add("block", "minecraft:mineable/shovel", ids("clay", "coarse_dirt", "dirt", "farmland", "grass_block", "gravel", "sand", "snow", "snow_block", "soul_sand"), false);
        s.add("block", "minecraft:mob_interactable_doors", ids("oak_door"), false);
        s.add("block", "minecraft:moss_replaceable", ids("andesite", "coarse_dirt", "diorite", "dirt", "granite", "grass_block", "stone"), false);
        s.add("block", "minecraft:needs_diamond_tool", ids("obsidian"), false);
        s.add("block", "minecraft:needs_iron_tool", ids("diamond_block", "diamond_ore", "emerald_block", "emerald_ore", "gold_block", "gold_ore", "redstone_ore"), false);
        s.add("block", "minecraft:needs_stone_tool", ids("iron_block", "iron_ore", "lapis_block", "lapis_ore"), false);
        s.add("block", "minecraft:nether_carver_replaceables", ids("andesite", "coarse_dirt", "diorite", "dirt", "granite", "grass_block", "netherrack", "soul_sand", "stone"), false);
        s.add("block", "minecraft:oak_logs", ids("oak_log"), false);
        s.add("block", "minecraft:occludes_vibration_signals", ids("black_wool", "blue_wool", "green_wool", "red_wool", "white_wool", "yellow_wool"), false);
        s.add("block", "minecraft:overworld_carver_replaceables", ids("andesite", "coarse_dirt", "diorite", "dirt", "granite", "grass_block", "gravel", "iron_ore", "sand", "sandstone", "snow", "stone", "terracotta", "water"), false);
        s.add("block", "minecraft:overworld_natural_logs", ids("birch_log", "oak_log", "spruce_log"), false);
        s.add("block", "minecraft:parrots_spawnable_on", ids("birch_leaves", "birch_log", "grass_block", "oak_leaves", "oak_log", "spruce_leaves", "spruce_log"), false);
        s.add("block", "minecraft:planks", ids("birch_planks", "oak_planks", "spruce_planks"), false);
        s.add("block", "minecraft:polar_bears_spawnable_on_alternate", ids("ice"), false);
        s.add("block", "minecraft:portals", ids("nether_portal"), false);
        s.add("block", "minecraft:pressure_plates", ids("oak_pressure_plate", "stone_pressure_plate"), false);
        s.add("block", "minecraft:prevent_mob_spawning_inside", ids("detector_rail", "powered_rail", "rail"), false);
        s.add("block", "minecraft:rabbits_spawnable_on", ids("grass_block", "sand", "snow", "snow_block"), false);
        s.add("block", "minecraft:rails", ids("detector_rail", "powered_rail", "rail"), false);
        s.add("block", "minecraft:redstone_ores", ids("redstone_ore"), false);
        s.add("block", "minecraft:replaceable", ids("dead_bush", "fern", "fire", "lava", "short_grass", "snow", "water"), false);
        s.add("block", "minecraft:replaceable_by_trees", ids("birch_leaves", "dead_bush", "fern", "oak_leaves", "short_grass", "spruce_leaves", "water"), false);
        s.add("block", "minecraft:sand", ids("sand"), false);
        s.add("block", "minecraft:saplings", ids("oak_sapling"), false);
        s.add("block", "minecraft:sculk_replaceable", ids("andesite", "clay", "coarse_dirt", "diorite", "dirt", "granite", "grass_block", "gravel", "netherrack", "sand", "sandstone", "soul_sand", "stone", "terracotta"), false);
        s.add("block", "minecraft:sculk_replaceable_world_gen", ids("andesite", "clay", "coarse_dirt", "diorite", "dirt", "granite", "grass_block", "gravel", "netherrack", "sand", "sandstone", "soul_sand", "stone", "terracotta"), false);
        s.add("block", "minecraft:slabs", ids("birch_slab", "brick_slab", "cobblestone_slab", "oak_slab", "sandstone_slab", "smooth_stone_slab", "spruce_slab", "stone_brick_slab"), false);
        s.add("block", "minecraft:small_dripleaf_placeable", ids("clay"), false);
        s.add("block", "minecraft:small_flowers", ids("blue_orchid", "dandelion", "poppy"), false);
        s.add("block", "minecraft:smelts_to_glass", ids("sand"), false);
        s.add("block", "minecraft:snaps_goat_horn", ids("birch_log", "coal_ore", "emerald_ore", "iron_ore", "oak_log", "spruce_log", "stone"), false);
        s.add("block", "minecraft:sniffer_diggable_block", ids("coarse_dirt", "dirt", "grass_block"), false);
        s.add("block", "minecraft:snow", ids("snow", "snow_block"), false);
        s.add("block", "minecraft:snow_layer_can_survive_on", ids("soul_sand"), false);
        s.add("block", "minecraft:snow_layer_cannot_survive_on", ids("ice"), false);
        s.add("block", "minecraft:soul_fire_base_blocks", ids("soul_sand"), false);
        s.add("block", "minecraft:soul_speed_blocks", ids("soul_sand"), false);
        s.add("block", "minecraft:spruce_logs", ids("spruce_log"), false);
        s.add("block", "minecraft:stairs", ids("birch_stairs", "brick_stairs", "cobblestone_stairs", "oak_stairs", "sandstone_stairs", "spruce_stairs", "stone_brick_stairs"), false);
        s.add("block", "minecraft:stone_bricks", ids("stone_bricks"), false);
        s.add("block", "minecraft:stone_buttons", ids("stone_button"), false);
        s.add("block", "minecraft:stone_ore_replaceables", ids("andesite", "diorite", "granite", "stone"), false);
        s.add("block", "minecraft:stone_pressure_plates", ids("stone_pressure_plate"), false);
        s.add("block", "minecraft:strider_warm_blocks", ids("lava"), false);
        s.add("block", "minecraft:sword_efficient", ids("birch_leaves", "blue_orchid", "brown_mushroom", "carrots", "dandelion", "dead_bush", "fern", "melon", "nether_wart", "oak_leaves", "oak_sapling", "poppy", "potatoes", "pumpkin", "red_mushroom", "short_grass", "spruce_leaves", "sugar_cane", "wheat"), false);
        s.add("block", "minecraft:terracotta", ids("terracotta"), false);
        s.add("block", "minecraft:trail_ruins_replaceable", ids("gravel"), false);
        s.add("block", "minecraft:trapdoors", ids("oak_trapdoor"), false);
        s.add("block", "minecraft:unstable_bottom_center", ids("oak_fence_gate"), false);
        s.add("block", "minecraft:valid_spawn", ids("grass_block"), false);
        s.add("block", "minecraft:wall_post_override", ids("oak_pressure_plate", "redstone_torch", "stone_pressure_plate", "torch"), false);
        s.add("block", "minecraft:walls", ids("cobblestone_wall"), false);
        s.add("block", "minecraft:wither_immune", ids("bedrock"), false);
        s.add("block", "minecraft:wither_summon_base_blocks", ids("soul_sand"), false);
        s.add("block", "minecraft:wolves_spawnable_on", ids("coarse_dirt", "grass_block", "snow", "snow_block"), false);
        s.add("block", "minecraft:wooden_buttons", ids("oak_button"), false);
        s.add("block", "minecraft:wooden_doors", ids("oak_door"), false);
        s.add("block", "minecraft:wooden_fences", ids("oak_fence"), false);
        s.add("block", "minecraft:wooden_pressure_plates", ids("oak_pressure_plate"), false);
        s.add("block", "minecraft:wooden_slabs", ids("birch_slab", "oak_slab", "spruce_slab"), false);
        s.add("block", "minecraft:wooden_stairs", ids("birch_stairs", "oak_stairs", "spruce_stairs"), false);
        s.add("block", "minecraft:wooden_trapdoors", ids("oak_trapdoor"), false);
        s.add("block", "minecraft:wool", ids("black_wool", "blue_wool", "green_wool", "red_wool", "white_wool", "yellow_wool"), false);
        s.add("block", "minecraft:wool_carpets", ids("black_carpet", "blue_carpet", "green_carpet", "red_carpet", "white_carpet", "yellow_carpet"), false);
        s.add("block", "neoforge:villager_farmlands", ids("farmland"), false);
        s.add("item", "c:animal_foods", ids("apple", "beef", "blue_orchid", "cactus", "carrot", "chicken", "cod", "cooked_beef", "cooked_chicken", "cooked_porkchop", "dandelion", "golden_apple", "golden_carrot", "poppy", "porkchop", "potato", "rotten_flesh", "salmon", "spider_eye", "sugar", "wheat", "wheat_seeds"), false);
        s.add("item", "c:armors", ids("chainmail_boots", "chainmail_chestplate", "chainmail_helmet", "chainmail_leggings", "diamond_boots", "diamond_chestplate", "diamond_helmet", "diamond_leggings", "golden_boots", "golden_chestplate", "golden_helmet", "golden_leggings", "iron_boots", "iron_chestplate", "iron_helmet", "iron_leggings", "leather_boots", "leather_chestplate", "leather_helmet", "leather_leggings"), false);
        s.add("item", "c:bones", ids("bone"), false);
        s.add("item", "c:bookshelves", ids("bookshelf"), false);
        s.add("item", "c:bricks", ids("brick", "nether_brick"), false);
        s.add("item", "c:bricks/nether", ids("nether_brick"), false);
        s.add("item", "c:bricks/normal", ids("brick"), false);
        s.add("item", "c:buckets", ids("bucket", "lava_bucket", "milk_bucket", "water_bucket"), false);
        s.add("item", "c:buckets/empty", ids("bucket"), false);
        s.add("item", "c:buckets/lava", ids("lava_bucket"), false);
        s.add("item", "c:buckets/milk", ids("milk_bucket"), false);
        s.add("item", "c:buckets/water", ids("water_bucket"), false);
        s.add("item", "c:chests", ids("chest"), false);
        s.add("item", "c:chests/wooden", ids("chest"), false);
        s.add("item", "c:cobblestones", ids("cobblestone", "mossy_cobblestone"), false);
        s.add("item", "c:cobblestones/mossy", ids("mossy_cobblestone"), false);
        s.add("item", "c:cobblestones/normal", ids("cobblestone"), false);
        s.add("item", "c:crops", ids("cactus", "carrot", "melon", "nether_wart", "potato", "pumpkin", "sugar_cane", "wheat"), false);
        s.add("item", "c:crops/cactus", ids("cactus"), false);
        s.add("item", "c:crops/carrot", ids("carrot"), false);
        s.add("item", "c:crops/melon", ids("melon"), false);
        s.add("item", "c:crops/nether_wart", ids("nether_wart"), false);
        s.add("item", "c:crops/potato", ids("potato"), false);
        s.add("item", "c:crops/pumpkin", ids("pumpkin"), false);
        s.add("item", "c:crops/sugar_cane", ids("sugar_cane"), false);
        s.add("item", "c:crops/wheat", ids("wheat"), false);
        s.add("item", "c:drinks", ids("milk_bucket", "potion"), false);
        s.add("item", "c:drinks/magic", ids("potion"), false);
        s.add("item", "c:drinks/milk", ids("milk_bucket"), false);
        s.add("item", "c:drinks/watery", ids("potion"), false);
        s.add("item", "c:dusts", ids("glowstone_dust", "redstone"), false);
        s.add("item", "c:dusts/glowstone", ids("glowstone_dust"), false);
        s.add("item", "c:dusts/redstone", ids("redstone"), false);
        s.add("item", "c:dyed", ids("black_carpet", "black_wool", "blue_carpet", "blue_wool", "green_carpet", "green_wool", "red_bed", "red_carpet", "red_wool", "white_carpet", "white_wool", "yellow_carpet", "yellow_wool"), false);
        s.add("item", "c:dyed/black", ids("black_carpet", "black_wool"), false);
        s.add("item", "c:dyed/blue", ids("blue_carpet", "blue_wool"), false);
        s.add("item", "c:dyed/green", ids("green_carpet", "green_wool"), false);
        s.add("item", "c:dyed/red", ids("red_bed", "red_carpet", "red_wool"), false);
        s.add("item", "c:dyed/white", ids("white_carpet", "white_wool"), false);
        s.add("item", "c:dyed/yellow", ids("yellow_carpet", "yellow_wool"), false);
        s.add("item", "c:eggs", ids("egg"), false);
        s.add("item", "c:enchantables", ids("bow", "chainmail_boots", "chainmail_chestplate", "chainmail_helmet", "chainmail_leggings", "diamond_axe", "diamond_boots", "diamond_chestplate", "diamond_helmet", "diamond_hoe", "diamond_leggings", "diamond_pickaxe", "diamond_shovel", "diamond_sword", "fishing_rod", "flint_and_steel", "golden_axe", "golden_boots", "golden_chestplate", "golden_helmet", "golden_hoe", "golden_leggings", "golden_pickaxe", "golden_shovel", "golden_sword", "iron_axe", "iron_boots", "iron_chestplate", "iron_helmet", "iron_hoe", "iron_leggings", "iron_pickaxe", "iron_shovel", "iron_sword", "leather_boots", "leather_chestplate", "leather_helmet", "leather_leggings", "shears", "stone_axe", "stone_hoe", "stone_pickaxe", "stone_shovel", "stone_sword", "wooden_axe", "wooden_hoe", "wooden_pickaxe", "wooden_shovel", "wooden_sword"), false);
        s.add("item", "c:ender_pearls", ids("ender_pearl"), false);
        s.add("item", "c:feathers", ids("feather"), false);
        s.add("item", "c:fence_gates", ids("oak_fence_gate"), false);
        s.add("item", "c:fence_gates/wooden", ids("oak_fence_gate"), false);
        s.add("item", "c:fences", ids("oak_fence"), false);
        s.add("item", "c:fences/wooden", ids("oak_fence"), false);
        s.add("item", "c:fertilizers", ids("bone_meal"), false);
        s.add("item", "c:foods", ids("apple", "baked_potato", "beef", "bread", "cake", "carrot", "chicken", "cod", "cooked_beef", "cooked_chicken", "cooked_cod", "cooked_porkchop", "cooked_salmon", "golden_apple", "golden_carrot", "melon_slice", "mushroom_stew", "porkchop", "potato", "pufferfish", "rotten_flesh", "salmon", "spider_eye", "tropical_fish"), false);
        s.add("item", "c:foods/bread", ids("bread"), false);
        s.add("item", "c:foods/cooked_fish", ids("cooked_cod", "cooked_salmon"), false);
        s.add("item", "c:foods/cooked_meat", ids("cooked_beef", "cooked_chicken", "cooked_porkchop"), false);
        s.add("item", "c:foods/edible_when_placed", ids("cake"), false);
        s.add("item", "c:foods/food_poisoning", ids("chicken", "pufferfish", "rotten_flesh", "spider_eye"), false);
        s.add("item", "c:foods/fruit", ids("apple", "golden_apple", "melon_slice"), false);
        s.add("item", "c:foods/golden", ids("golden_apple", "golden_carrot"), false);
        s.add("item", "c:foods/raw_fish", ids("cod", "pufferfish", "salmon", "tropical_fish"), false);
        s.add("item", "c:foods/raw_meat", ids("beef", "chicken", "porkchop"), false);
        s.add("item", "c:foods/soup", ids("mushroom_stew"), false);
        s.add("item", "c:foods/vegetable", ids("carrot", "golden_carrot", "potato"), false);
        s.add("item", "c:gems", ids("diamond", "emerald", "lapis_lazuli", "quartz"), false);
        s.add("item", "c:gems/diamond", ids("diamond"), false);
        s.add("item", "c:gems/emerald", ids("emerald"), false);
        s.add("item", "c:gems/lapis", ids("lapis_lazuli"), false);
        s.add("item", "c:gems/quartz", ids("quartz"), false);
        s.add("item", "c:glass_blocks", ids("glass"), false);
        s.add("item", "c:glass_blocks/cheap", ids("glass"), false);
        s.add("item", "c:glass_blocks/colorless", ids("glass"), false);
        s.add("item", "c:glass_panes", ids("glass_pane"), false);
        s.add("item", "c:glass_panes/colorless", ids("glass_pane"), false);
        s.add("item", "c:gravels", ids("gravel"), false);
        s.add("item", "c:gunpowders", ids("gunpowder"), false);
        s.add("item", "c:ingots", ids("gold_ingot", "iron_ingot"), false);
        s.add("item", "c:ingots/gold", ids("gold_ingot"), false);
        s.add("item", "c:ingots/iron", ids("iron_ingot"), false);
        s.add("item", "c:leathers", ids("leather"), false);
        s.add("item", "c:mushrooms", ids("brown_mushroom", "red_mushroom"), false);
        s.add("item", "c:netherracks", ids("netherrack"), false);
        s.add("item", "c:nuggets", ids("gold_nugget"), false);
        s.add("item", "c:nuggets/gold", ids("gold_nugget"), false);
        s.add("item", "c:obsidians", ids("obsidian"), false);
        s.add("item", "c:obsidians/normal", ids("obsidian"), false);
        s.add("item", "c:ore_bearing_ground/netherrack", ids("netherrack"), false);
        s.add("item", "c:ore_bearing_ground/stone", ids("stone"), false);
        s.add("item", "c:ore_rates/dense", ids("lapis_ore", "redstone_ore"), false);
        s.add("item", "c:ore_rates/singular", ids("coal_ore", "diamond_ore", "emerald_ore", "gold_ore", "iron_ore", "nether_quartz_ore"), false);
        s.add("item", "c:ores", ids("coal_ore", "diamond_ore", "emerald_ore", "gold_ore", "iron_ore", "lapis_ore", "nether_quartz_ore", "redstone_ore"), false);
        s.add("item", "c:ores/coal", ids("coal_ore"), false);
        s.add("item", "c:ores/diamond", ids("diamond_ore"), false);
        s.add("item", "c:ores/emerald", ids("emerald_ore"), false);
        s.add("item", "c:ores/gold", ids("gold_ore"), false);
        s.add("item", "c:ores/iron", ids("iron_ore"), false);
        s.add("item", "c:ores/lapis", ids("lapis_ore"), false);
        s.add("item", "c:ores/quartz", ids("nether_quartz_ore"), false);
        s.add("item", "c:ores/redstone", ids("redstone_ore"), false);
        s.add("item", "c:ores_in_ground/netherrack", ids("nether_quartz_ore"), false);
        s.add("item", "c:ores_in_ground/stone", ids("coal_ore", "diamond_ore", "emerald_ore", "gold_ore", "iron_ore", "lapis_ore", "redstone_ore"), false);
        s.add("item", "c:player_workstations/crafting_tables", ids("crafting_table"), false);
        s.add("item", "c:player_workstations/furnaces", ids("furnace"), false);
        s.add("item", "c:potions", ids("potion", "splash_potion"), false);
        s.add("item", "c:potions/bottle", ids("potion", "splash_potion"), false);
        s.add("item", "c:pumpkins", ids("pumpkin"), false);
        s.add("item", "c:pumpkins/normal", ids("pumpkin"), false);
        s.add("item", "c:rods", ids("blaze_rod", "stick"), false);
        s.add("item", "c:rods/blaze", ids("blaze_rod"), false);
        s.add("item", "c:rods/wooden", ids("stick"), false);
        s.add("item", "c:sands", ids("sand"), false);
        s.add("item", "c:sands/colorless", ids("sand"), false);
        s.add("item", "c:sandstone/blocks", ids("sandstone"), false);
        s.add("item", "c:sandstone/slabs", ids("sandstone_slab"), false);
        s.add("item", "c:sandstone/stairs", ids("sandstone_stairs"), false);
        s.add("item", "c:sandstone/uncolored_blocks", ids("sandstone"), false);
        s.add("item", "c:sandstone/uncolored_slabs", ids("sandstone_slab"), false);
        s.add("item", "c:sandstone/uncolored_stairs", ids("sandstone_stairs"), false);
        s.add("item", "c:seeds", ids("wheat_seeds"), false);
        s.add("item", "c:seeds/wheat", ids("wheat_seeds"), false);
        s.add("item", "c:stones", ids("andesite", "diorite", "granite", "stone"), false);
        s.add("item", "c:storage_blocks", ids("diamond_block", "emerald_block", "gold_block", "iron_block", "lapis_block", "redstone_block"), false);
        s.add("item", "c:storage_blocks/diamond", ids("diamond_block"), false);
        s.add("item", "c:storage_blocks/emerald", ids("emerald_block"), false);
        s.add("item", "c:storage_blocks/gold", ids("gold_block"), false);
        s.add("item", "c:storage_blocks/iron", ids("iron_block"), false);
        s.add("item", "c:storage_blocks/lapis", ids("lapis_block"), false);
        s.add("item", "c:storage_blocks/redstone", ids("redstone_block"), false);
        s.add("item", "c:strings", ids("string"), false);
        s.add("item", "c:tools", ids("bow", "diamond_axe", "diamond_hoe", "diamond_pickaxe", "diamond_shovel", "diamond_sword", "fishing_rod", "flint_and_steel", "golden_axe", "golden_hoe", "golden_pickaxe", "golden_shovel", "golden_sword", "iron_axe", "iron_hoe", "iron_pickaxe", "iron_shovel", "iron_sword", "shears", "stone_axe", "stone_hoe", "stone_pickaxe", "stone_shovel", "stone_sword", "wooden_axe", "wooden_hoe", "wooden_pickaxe", "wooden_shovel", "wooden_sword"), false);
        s.add("item", "c:tools/bow", ids("bow"), false);
        s.add("item", "c:tools/fishing_rod", ids("fishing_rod"), false);
        s.add("item", "c:tools/igniter", ids("flint_and_steel"), false);
        s.add("item", "c:tools/melee_weapon", ids("diamond_axe", "diamond_sword", "golden_axe", "golden_sword", "iron_axe", "iron_sword", "stone_axe", "stone_sword", "wooden_axe", "wooden_sword"), false);
        s.add("item", "c:tools/mining_tool", ids("diamond_pickaxe", "golden_pickaxe", "iron_pickaxe", "stone_pickaxe", "wooden_pickaxe"), false);
        s.add("item", "c:tools/ranged_weapon", ids("bow"), false);
        s.add("item", "c:tools/shear", ids("shears"), false);
        s.add("item", "c:villager_job_sites", ids("brewing_stand"), false);
        s.add("item", "minecraft:anvil", ids("anvil"), false);
        s.add("item", "minecraft:armadillo_food", ids("spider_eye"), false);
        s.add("item", "minecraft:arrows", ids("arrow"), false);
        s.add("item", "minecraft:axes", ids("diamond_axe", "golden_axe", "iron_axe", "stone_axe", "wooden_axe"), false);
        s.add("item", "minecraft:beacon_payment_items", ids("diamond", "emerald", "gold_ingot", "iron_ingot"), false);
        s.add("item", "minecraft:beds", ids("red_bed"), false);
        s.add("item", "minecraft:bee_food", ids("blue_orchid", "dandelion", "poppy"), false);
        s.add("item", "minecraft:birch_logs", ids("birch_log"), false);
        s.add("item", "minecraft:boats", ids("oak_boat"), false);
        s.add("item", "minecraft:bookshelf_books", ids("book", "enchanted_book"), false);
        s.add("item", "minecraft:breaks_decorated_pots", ids("diamond_axe", "diamond_hoe", "diamond_pickaxe", "diamond_shovel", "diamond_sword", "golden_axe", "golden_hoe", "golden_pickaxe", "golden_shovel", "golden_sword", "iron_axe", "iron_hoe", "iron_pickaxe", "iron_shovel", "iron_sword", "stone_axe", "stone_hoe", "stone_pickaxe", "stone_shovel", "stone_sword", "wooden_axe", "wooden_hoe", "wooden_pickaxe", "wooden_shovel", "wooden_sword"), false);
        s.add("item", "minecraft:buttons", ids("oak_button", "stone_button"), false);
        s.add("item", "minecraft:camel_food", ids("cactus"), false);
        s.add("item", "minecraft:cat_food", ids("cod", "salmon"), false);
        s.add("item", "minecraft:chest_armor", ids("chainmail_chestplate", "diamond_chestplate", "golden_chestplate", "iron_chestplate", "leather_chestplate"), false);
        s.add("item", "minecraft:chicken_food", ids("wheat_seeds"), false);
        s.add("item", "minecraft:cluster_max_harvestables", ids("diamond_pickaxe", "golden_pickaxe", "iron_pickaxe", "stone_pickaxe", "wooden_pickaxe"), false);
        s.add("item", "minecraft:coal_ores", ids("coal_ore"), false);
        s.add("item", "minecraft:coals", ids("charcoal", "coal"), false);
        s.add("item", "minecraft:completes_find_tree_tutorial", ids("birch_leaves", "birch_log", "oak_leaves", "oak_log", "spruce_leaves", "spruce_log"), false);
        s.add("item", "minecraft:cow_food", ids("wheat"), false);
        s.add("item", "minecraft:creeper_igniters", ids("fire_charge", "flint_and_steel"), false);
        s.add("item", "minecraft:dampens_vibrations", ids("black_carpet", "black_wool", "blue_carpet", "blue_wool", "green_carpet", "green_wool", "red_carpet", "red_wool", "white_carpet", "white_wool", "yellow_carpet", "yellow_wool"), false);
        s.add("item", "minecraft:decorated_pot_ingredients", ids("brick"), false);
        s.add("item", "minecraft:diamond_ores", ids("diamond_ore"), false);
        s.add("item", "minecraft:dirt", ids("coarse_dirt", "dirt", "grass_block"), false);
        s.add("item", "minecraft:doors", ids("iron_door", "oak_door"), false);
        s.add("item", "minecraft:dyeable", ids("leather_boots", "leather_chestplate", "leather_helmet", "leather_leggings"), false);
        s.add("item", "minecraft:emerald_ores", ids("emerald_ore"), false);
        s.add("item", "minecraft:enchantable/armor", ids("chainmail_boots", "chainmail_chestplate", "chainmail_helmet", "chainmail_leggings", "diamond_boots", "diamond_chestplate", "diamond_helmet", "diamond_leggings", "golden_boots", "golden_chestplate", "golden_helmet", "golden_leggings", "iron_boots", "iron_chestplate", "iron_helmet", "iron_leggings", "leather_boots", "leather_chestplate", "leather_helmet", "leather_leggings"), false);
        s.add("item", "minecraft:enchantable/bow", ids("bow"), false);
        s.add("item", "minecraft:enchantable/chest_armor", ids("chainmail_chestplate", "diamond_chestplate", "golden_chestplate", "iron_chestplate", "leather_chestplate"), false);
        s.add("item", "minecraft:enchantable/durability", ids("bow", "chainmail_boots", "chainmail_chestplate", "chainmail_helmet", "chainmail_leggings", "diamond_axe", "diamond_boots", "diamond_chestplate", "diamond_helmet", "diamond_hoe", "diamond_leggings", "diamond_pickaxe", "diamond_shovel", "diamond_sword", "fishing_rod", "flint_and_steel", "golden_axe", "golden_boots", "golden_chestplate", "golden_helmet", "golden_hoe", "golden_leggings", "golden_pickaxe", "golden_shovel", "golden_sword", "iron_axe", "iron_boots", "iron_chestplate", "iron_helmet", "iron_hoe", "iron_leggings", "iron_pickaxe", "iron_shovel", "iron_sword", "leather_boots", "leather_chestplate", "leather_helmet", "leather_leggings", "shears", "stone_axe", "stone_hoe", "stone_pickaxe", "stone_shovel", "stone_sword", "wooden_axe", "wooden_hoe", "wooden_pickaxe", "wooden_shovel", "wooden_sword"), false);
        s.add("item", "minecraft:enchantable/equippable", ids("chainmail_boots", "chainmail_chestplate", "chainmail_helmet", "chainmail_leggings", "diamond_boots", "diamond_chestplate", "diamond_helmet", "diamond_leggings", "golden_boots", "golden_chestplate", "golden_helmet", "golden_leggings", "iron_boots", "iron_chestplate", "iron_helmet", "iron_leggings", "leather_boots", "leather_chestplate", "leather_helmet", "leather_leggings"), false);
        s.add("item", "minecraft:enchantable/fire_aspect", ids("diamond_sword", "golden_sword", "iron_sword", "stone_sword", "wooden_sword"), false);
        s.add("item", "minecraft:enchantable/fishing", ids("fishing_rod"), false);
        s.add("item", "minecraft:enchantable/foot_armor", ids("chainmail_boots", "diamond_boots", "golden_boots", "iron_boots", "leather_boots"), false);
        s.add("item", "minecraft:enchantable/head_armor", ids("chainmail_helmet", "diamond_helmet", "golden_helmet", "iron_helmet", "leather_helmet"), false);
        s.add("item", "minecraft:enchantable/leg_armor", ids("chainmail_leggings", "diamond_leggings", "golden_leggings", "iron_leggings", "leather_leggings"), false);
        s.add("item", "minecraft:enchantable/mining", ids("diamond_axe", "diamond_hoe", "diamond_pickaxe", "diamond_shovel", "golden_axe", "golden_hoe", "golden_pickaxe", "golden_shovel", "iron_axe", "iron_hoe", "iron_pickaxe", "iron_shovel", "shears", "stone_axe", "stone_hoe", "stone_pickaxe", "stone_shovel", "wooden_axe", "wooden_hoe", "wooden_pickaxe", "wooden_shovel"), false);
        s.add("item", "minecraft:enchantable/mining_loot", ids("diamond_axe", "diamond_hoe", "diamond_pickaxe", "diamond_shovel", "golden_axe", "golden_hoe", "golden_pickaxe", "golden_shovel", "iron_axe", "iron_hoe", "iron_pickaxe", "iron_shovel", "stone_axe", "stone_hoe", "stone_pickaxe", "stone_shovel", "wooden_axe", "wooden_hoe", "wooden_pickaxe", "wooden_shovel"), false);
        s.add("item", "minecraft:enchantable/sharp_weapon", ids("diamond_axe", "diamond_sword", "golden_axe", "golden_sword", "iron_axe", "iron_sword", "stone_axe", "stone_sword", "wooden_axe", "wooden_sword"), false);
        s.add("item", "minecraft:enchantable/sword", ids("diamond_sword", "golden_sword", "iron_sword", "stone_sword", "wooden_sword"), false);
        s.add("item", "minecraft:enchantable/vanishing", ids("bow", "chainmail_boots", "chainmail_chestplate", "chainmail_helmet", "chainmail_leggings", "diamond_axe", "diamond_boots", "diamond_chestplate", "diamond_helmet", "diamond_hoe", "diamond_leggings", "diamond_pickaxe", "diamond_shovel", "diamond_sword", "fishing_rod", "flint_and_steel", "golden_axe", "golden_boots", "golden_chestplate", "golden_helmet", "golden_hoe", "golden_leggings", "golden_pickaxe", "golden_shovel", "golden_sword", "iron_axe", "iron_boots", "iron_chestplate", "iron_helmet", "iron_hoe", "iron_leggings", "iron_pickaxe", "iron_shovel", "iron_sword", "leather_boots", "leather_chestplate", "leather_helmet", "leather_leggings", "shears", "stone_axe", "stone_hoe", "stone_pickaxe", "stone_shovel", "stone_sword", "wooden_axe", "wooden_hoe", "wooden_pickaxe", "wooden_shovel", "wooden_sword"), false);
        s.add("item", "minecraft:enchantable/weapon", ids("diamond_axe", "diamond_sword", "golden_axe", "golden_sword", "iron_axe", "iron_sword", "stone_axe", "stone_sword", "wooden_axe", "wooden_sword"), false);
        s.add("item", "minecraft:fence_gates", ids("oak_fence_gate"), false);
        s.add("item", "minecraft:fences", ids("oak_fence"), false);
        s.add("item", "minecraft:fishes", ids("cod", "cooked_cod", "cooked_salmon", "pufferfish", "salmon", "tropical_fish"), false);
        s.add("item", "minecraft:flowers", ids("blue_orchid", "dandelion", "poppy"), false);
        s.add("item", "minecraft:foot_armor", ids("chainmail_boots", "diamond_boots", "golden_boots", "iron_boots", "leather_boots"), false);
        s.add("item", "minecraft:freeze_immune_wearables", ids("leather_boots", "leather_chestplate", "leather_helmet", "leather_leggings"), false);
        s.add("item", "minecraft:goat_food", ids("wheat"), false);
        s.add("item", "minecraft:gold_ores", ids("gold_ore"), false);
        s.add("item", "minecraft:head_armor", ids("chainmail_helmet", "diamond_helmet", "golden_helmet", "iron_helmet", "leather_helmet"), false);
        s.add("item", "minecraft:hoes", ids("diamond_hoe", "golden_hoe", "iron_hoe", "stone_hoe", "wooden_hoe"), false);
        s.add("item", "minecraft:horse_food", ids("apple", "golden_apple", "golden_carrot", "sugar", "wheat"), false);
        s.add("item", "minecraft:horse_tempt_items", ids("golden_apple", "golden_carrot"), false);
        s.add("item", "minecraft:ignored_by_piglin_babies", ids("leather"), false);
        s.add("item", "minecraft:iron_ores", ids("iron_ore"), false);
        s.add("item", "minecraft:lapis_ores", ids("lapis_ore"), false);
        s.add("item", "minecraft:leaves", ids("birch_leaves", "oak_leaves", "spruce_leaves"), false);
        s.add("item", "minecraft:leg_armor", ids("chainmail_leggings", "diamond_leggings", "golden_leggings", "iron_leggings", "leather_leggings"), false);
        s.add("item", "minecraft:llama_food", ids("wheat"), false);
        s.add("item", "minecraft:logs", ids("birch_log", "oak_log", "spruce_log"), false);
        s.add("item", "minecraft:logs_that_burn", ids("birch_log", "oak_log", "spruce_log"), false);
        s.add("item", "minecraft:meat", ids("beef", "chicken", "cooked_beef", "cooked_chicken", "cooked_porkchop", "porkchop", "rotten_flesh"), false);
        s.add("item", "minecraft:oak_logs", ids("oak_log"), false);
        s.add("item", "minecraft:ocelot_food", ids("cod", "salmon"), false);
        s.add("item", "minecraft:parrot_food", ids("wheat_seeds"), false);
        s.add("item", "minecraft:pickaxes", ids("diamond_pickaxe", "golden_pickaxe", "iron_pickaxe", "stone_pickaxe", "wooden_pickaxe"), false);
        s.add("item", "minecraft:pig_food", ids("carrot", "potato"), false);
        s.add("item", "minecraft:piglin_food", ids("cooked_porkchop", "porkchop"), false);
        s.add("item", "minecraft:piglin_loved", ids("glistering_melon_slice", "gold_block", "gold_ingot", "gold_ore", "golden_apple", "golden_axe", "golden_boots", "golden_carrot", "golden_chestplate", "golden_helmet", "golden_hoe", "golden_leggings", "golden_pickaxe", "golden_shovel", "golden_sword"), false);
        s.add("item", "minecraft:planks", ids("birch_planks", "oak_planks", "spruce_planks"), false);
        s.add("item", "minecraft:rabbit_food", ids("carrot", "dandelion", "golden_carrot"), false);
        s.add("item", "minecraft:rails", ids("detector_rail", "powered_rail", "rail"), false);
        s.add("item", "minecraft:redstone_ores", ids("redstone_ore"), false);
        s.add("item", "minecraft:sand", ids("sand"), false);
        s.add("item", "minecraft:saplings", ids("oak_sapling"), false);
        s.add("item", "minecraft:sheep_food", ids("wheat"), false);
        s.add("item", "minecraft:shovels", ids("diamond_shovel", "golden_shovel", "iron_shovel", "stone_shovel", "wooden_shovel"), false);
        s.add("item", "minecraft:slabs", ids("birch_slab", "brick_slab", "cobblestone_slab", "oak_slab", "sandstone_slab", "smooth_stone_slab", "spruce_slab", "stone_brick_slab"), false);
        s.add("item", "minecraft:small_flowers", ids("blue_orchid", "dandelion", "poppy"), false);
        s.add("item", "minecraft:smelts_to_glass", ids("sand"), false);
        s.add("item", "minecraft:soul_fire_base_blocks", ids("soul_sand"), false);
        s.add("item", "minecraft:spruce_logs", ids("spruce_log"), false);
        s.add("item", "minecraft:stairs", ids("birch_stairs", "brick_stairs", "cobblestone_stairs", "oak_stairs", "sandstone_stairs", "spruce_stairs", "stone_brick_stairs"), false);
        s.add("item", "minecraft:stone_bricks", ids("stone_bricks"), false);
        s.add("item", "minecraft:stone_buttons", ids("stone_button"), false);
        s.add("item", "minecraft:stone_crafting_materials", ids("cobblestone"), false);
        s.add("item", "minecraft:stone_tool_materials", ids("cobblestone"), false);
        s.add("item", "minecraft:swords", ids("diamond_sword", "golden_sword", "iron_sword", "stone_sword", "wooden_sword"), false);
        s.add("item", "minecraft:terracotta", ids("terracotta"), false);
        s.add("item", "minecraft:trapdoors", ids("oak_trapdoor"), false);
        s.add("item", "minecraft:trim_materials", ids("diamond", "emerald", "gold_ingot", "iron_ingot", "lapis_lazuli", "quartz", "redstone"), false);
        s.add("item", "minecraft:trimmable_armor", ids("chainmail_boots", "chainmail_chestplate", "chainmail_helmet", "chainmail_leggings", "diamond_boots", "diamond_chestplate", "diamond_helmet", "diamond_leggings", "golden_boots", "golden_chestplate", "golden_helmet", "golden_leggings", "iron_boots", "iron_chestplate", "iron_helmet", "iron_leggings", "leather_boots", "leather_chestplate", "leather_helmet", "leather_leggings"), false);
        s.add("item", "minecraft:villager_plantable_seeds", ids("carrot", "potato", "wheat_seeds"), false);
        s.add("item", "minecraft:walls", ids("cobblestone_wall"), false);
        s.add("item", "minecraft:wolf_food", ids("beef", "chicken", "cooked_beef", "cooked_chicken", "cooked_porkchop", "porkchop", "rotten_flesh"), false);
        s.add("item", "minecraft:wooden_buttons", ids("oak_button"), false);
        s.add("item", "minecraft:wooden_doors", ids("oak_door"), false);
        s.add("item", "minecraft:wooden_fences", ids("oak_fence"), false);
        s.add("item", "minecraft:wooden_pressure_plates", ids("oak_pressure_plate"), false);
        s.add("item", "minecraft:wooden_slabs", ids("birch_slab", "oak_slab", "spruce_slab"), false);
        s.add("item", "minecraft:wooden_stairs", ids("birch_stairs", "oak_stairs", "spruce_stairs"), false);
        s.add("item", "minecraft:wooden_trapdoors", ids("oak_trapdoor"), false);
        s.add("item", "minecraft:wool", ids("black_wool", "blue_wool", "green_wool", "red_wool", "white_wool", "yellow_wool"), false);
        s.add("item", "minecraft:wool_carpets", ids("black_carpet", "blue_carpet", "green_carpet", "red_carpet", "white_carpet", "yellow_carpet"), false);
        s.add("item", "neoforge:enchanting_fuels", ids("lapis_lazuli"), false);
        s.add("fluid", "minecraft:water", ids("water", "flowing_water"), false);
        s.add("fluid", "minecraft:lava", ids("lava", "flowing_lava"), false);
    }

    private static List<String> ids(String... names) {
        return java.util.Arrays.stream(names).map(n -> n.contains(":") ? n : "minecraft:" + n).toList();
    }
}
