package net.minecraft.tags;

import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;

/** Minecraft's item tag keys; their contents come from tag files (reamc-compat, see mc.mod.Tags). */
@SuppressWarnings({"unchecked", "rawtypes"})
public final class ItemTags {
    private ItemTags() { }

    private static TagKey<Item> tag(String ns, String path) { return create(ResourceLocation.fromNamespaceAndPath(ns, path)); }

    public static TagKey<Item> create(ResourceLocation id) { return TagKey.create((net.minecraft.resources.ResourceKey) Registries.ITEM, id); }

    public static final TagKey<Item> WOOL = tag("minecraft", "wool");
    public static final TagKey<Item> PLANKS = tag("minecraft", "planks");
    public static final TagKey<Item> STONE_BRICKS = tag("minecraft", "stone_bricks");
    public static final TagKey<Item> WOODEN_BUTTONS = tag("minecraft", "wooden_buttons");
    public static final TagKey<Item> STONE_BUTTONS = tag("minecraft", "stone_buttons");
    public static final TagKey<Item> BUTTONS = tag("minecraft", "buttons");
    public static final TagKey<Item> WOOL_CARPETS = tag("minecraft", "wool_carpets");
    public static final TagKey<Item> WOODEN_DOORS = tag("minecraft", "wooden_doors");
    public static final TagKey<Item> WOODEN_STAIRS = tag("minecraft", "wooden_stairs");
    public static final TagKey<Item> WOODEN_SLABS = tag("minecraft", "wooden_slabs");
    public static final TagKey<Item> WOODEN_FENCES = tag("minecraft", "wooden_fences");
    public static final TagKey<Item> FENCE_GATES = tag("minecraft", "fence_gates");
    public static final TagKey<Item> WOODEN_PRESSURE_PLATES = tag("minecraft", "wooden_pressure_plates");
    public static final TagKey<Item> WOODEN_TRAPDOORS = tag("minecraft", "wooden_trapdoors");
    public static final TagKey<Item> DOORS = tag("minecraft", "doors");
    public static final TagKey<Item> SAPLINGS = tag("minecraft", "saplings");
    public static final TagKey<Item> LOGS_THAT_BURN = tag("minecraft", "logs_that_burn");
    public static final TagKey<Item> LOGS = tag("minecraft", "logs");
    public static final TagKey<Item> DARK_OAK_LOGS = tag("minecraft", "dark_oak_logs");
    public static final TagKey<Item> OAK_LOGS = tag("minecraft", "oak_logs");
    public static final TagKey<Item> BIRCH_LOGS = tag("minecraft", "birch_logs");
    public static final TagKey<Item> ACACIA_LOGS = tag("minecraft", "acacia_logs");
    public static final TagKey<Item> CHERRY_LOGS = tag("minecraft", "cherry_logs");
    public static final TagKey<Item> JUNGLE_LOGS = tag("minecraft", "jungle_logs");
    public static final TagKey<Item> SPRUCE_LOGS = tag("minecraft", "spruce_logs");
    public static final TagKey<Item> MANGROVE_LOGS = tag("minecraft", "mangrove_logs");
    public static final TagKey<Item> CRIMSON_STEMS = tag("minecraft", "crimson_stems");
    public static final TagKey<Item> WARPED_STEMS = tag("minecraft", "warped_stems");
    public static final TagKey<Item> BAMBOO_BLOCKS = tag("minecraft", "bamboo_blocks");
    public static final TagKey<Item> WART_BLOCKS = tag("minecraft", "wart_blocks");
    public static final TagKey<Item> BANNERS = tag("minecraft", "banners");
    public static final TagKey<Item> SAND = tag("minecraft", "sand");
    public static final TagKey<Item> SMELTS_TO_GLASS = tag("minecraft", "smelts_to_glass");
    public static final TagKey<Item> STAIRS = tag("minecraft", "stairs");
    public static final TagKey<Item> SLABS = tag("minecraft", "slabs");
    public static final TagKey<Item> WALLS = tag("minecraft", "walls");
    public static final TagKey<Item> ANVIL = tag("minecraft", "anvil");
    public static final TagKey<Item> RAILS = tag("minecraft", "rails");
    public static final TagKey<Item> LEAVES = tag("minecraft", "leaves");
    public static final TagKey<Item> TRAPDOORS = tag("minecraft", "trapdoors");
    public static final TagKey<Item> SMALL_FLOWERS = tag("minecraft", "small_flowers");
    public static final TagKey<Item> BEDS = tag("minecraft", "beds");
    public static final TagKey<Item> FENCES = tag("minecraft", "fences");
    public static final TagKey<Item> TALL_FLOWERS = tag("minecraft", "tall_flowers");
    public static final TagKey<Item> FLOWERS = tag("minecraft", "flowers");
    public static final TagKey<Item> PIGLIN_REPELLENTS = tag("minecraft", "piglin_repellents");
    public static final TagKey<Item> PIGLIN_LOVED = tag("minecraft", "piglin_loved");
    public static final TagKey<Item> IGNORED_BY_PIGLIN_BABIES = tag("minecraft", "ignored_by_piglin_babies");
    public static final TagKey<Item> MEAT = tag("minecraft", "meat");
    public static final TagKey<Item> SNIFFER_FOOD = tag("minecraft", "sniffer_food");
    public static final TagKey<Item> PIGLIN_FOOD = tag("minecraft", "piglin_food");
    public static final TagKey<Item> FOX_FOOD = tag("minecraft", "fox_food");
    public static final TagKey<Item> COW_FOOD = tag("minecraft", "cow_food");
    public static final TagKey<Item> GOAT_FOOD = tag("minecraft", "goat_food");
    public static final TagKey<Item> SHEEP_FOOD = tag("minecraft", "sheep_food");
    public static final TagKey<Item> WOLF_FOOD = tag("minecraft", "wolf_food");
    public static final TagKey<Item> CAT_FOOD = tag("minecraft", "cat_food");
    public static final TagKey<Item> HORSE_FOOD = tag("minecraft", "horse_food");
    public static final TagKey<Item> HORSE_TEMPT_ITEMS = tag("minecraft", "horse_tempt_items");
    public static final TagKey<Item> CAMEL_FOOD = tag("minecraft", "camel_food");
    public static final TagKey<Item> ARMADILLO_FOOD = tag("minecraft", "armadillo_food");
    public static final TagKey<Item> BEE_FOOD = tag("minecraft", "bee_food");
    public static final TagKey<Item> CHICKEN_FOOD = tag("minecraft", "chicken_food");
    public static final TagKey<Item> FROG_FOOD = tag("minecraft", "frog_food");
    public static final TagKey<Item> HOGLIN_FOOD = tag("minecraft", "hoglin_food");
    public static final TagKey<Item> LLAMA_FOOD = tag("minecraft", "llama_food");
    public static final TagKey<Item> LLAMA_TEMPT_ITEMS = tag("minecraft", "llama_tempt_items");
    public static final TagKey<Item> OCELOT_FOOD = tag("minecraft", "ocelot_food");
    public static final TagKey<Item> PANDA_FOOD = tag("minecraft", "panda_food");
    public static final TagKey<Item> PIG_FOOD = tag("minecraft", "pig_food");
    public static final TagKey<Item> RABBIT_FOOD = tag("minecraft", "rabbit_food");
    public static final TagKey<Item> STRIDER_FOOD = tag("minecraft", "strider_food");
    public static final TagKey<Item> STRIDER_TEMPT_ITEMS = tag("minecraft", "strider_tempt_items");
    public static final TagKey<Item> TURTLE_FOOD = tag("minecraft", "turtle_food");
    public static final TagKey<Item> PARROT_FOOD = tag("minecraft", "parrot_food");
    public static final TagKey<Item> PARROT_POISONOUS_FOOD = tag("minecraft", "parrot_poisonous_food");
    public static final TagKey<Item> AXOLOTL_FOOD = tag("minecraft", "axolotl_food");
    public static final TagKey<Item> GOLD_ORES = tag("minecraft", "gold_ores");
    public static final TagKey<Item> IRON_ORES = tag("minecraft", "iron_ores");
    public static final TagKey<Item> DIAMOND_ORES = tag("minecraft", "diamond_ores");
    public static final TagKey<Item> REDSTONE_ORES = tag("minecraft", "redstone_ores");
    public static final TagKey<Item> LAPIS_ORES = tag("minecraft", "lapis_ores");
    public static final TagKey<Item> COAL_ORES = tag("minecraft", "coal_ores");
    public static final TagKey<Item> EMERALD_ORES = tag("minecraft", "emerald_ores");
    public static final TagKey<Item> COPPER_ORES = tag("minecraft", "copper_ores");
    public static final TagKey<Item> NON_FLAMMABLE_WOOD = tag("minecraft", "non_flammable_wood");
    public static final TagKey<Item> SOUL_FIRE_BASE_BLOCKS = tag("minecraft", "soul_fire_base_blocks");
    public static final TagKey<Item> CANDLES = tag("minecraft", "candles");
    public static final TagKey<Item> DIRT = tag("minecraft", "dirt");
    public static final TagKey<Item> TERRACOTTA = tag("minecraft", "terracotta");
    public static final TagKey<Item> COMPLETES_FIND_TREE_TUTORIAL = tag("minecraft", "completes_find_tree_tutorial");
    public static final TagKey<Item> BOATS = tag("minecraft", "boats");
    public static final TagKey<Item> CHEST_BOATS = tag("minecraft", "chest_boats");
    public static final TagKey<Item> FISHES = tag("minecraft", "fishes");
    public static final TagKey<Item> SIGNS = tag("minecraft", "signs");
    public static final TagKey<Item> CREEPER_DROP_MUSIC_DISCS = tag("minecraft", "creeper_drop_music_discs");
    public static final TagKey<Item> COALS = tag("minecraft", "coals");
    public static final TagKey<Item> ARROWS = tag("minecraft", "arrows");
    public static final TagKey<Item> LECTERN_BOOKS = tag("minecraft", "lectern_books");
    public static final TagKey<Item> BOOKSHELF_BOOKS = tag("minecraft", "bookshelf_books");
    public static final TagKey<Item> BEACON_PAYMENT_ITEMS = tag("minecraft", "beacon_payment_items");
    public static final TagKey<Item> STONE_TOOL_MATERIALS = tag("minecraft", "stone_tool_materials");
    public static final TagKey<Item> STONE_CRAFTING_MATERIALS = tag("minecraft", "stone_crafting_materials");
    public static final TagKey<Item> FREEZE_IMMUNE_WEARABLES = tag("minecraft", "freeze_immune_wearables");
    public static final TagKey<Item> DAMPENS_VIBRATIONS = tag("minecraft", "dampens_vibrations");
    public static final TagKey<Item> CLUSTER_MAX_HARVESTABLES = tag("minecraft", "cluster_max_harvestables");
    public static final TagKey<Item> COMPASSES = tag("minecraft", "compasses");
    public static final TagKey<Item> HANGING_SIGNS = tag("minecraft", "hanging_signs");
    public static final TagKey<Item> CREEPER_IGNITERS = tag("minecraft", "creeper_igniters");
    public static final TagKey<Item> NOTE_BLOCK_TOP_INSTRUMENTS = tag("minecraft", "noteblock_top_instruments");
    public static final TagKey<Item> FOOT_ARMOR = tag("minecraft", "foot_armor");
    public static final TagKey<Item> LEG_ARMOR = tag("minecraft", "leg_armor");
    public static final TagKey<Item> CHEST_ARMOR = tag("minecraft", "chest_armor");
    public static final TagKey<Item> HEAD_ARMOR = tag("minecraft", "head_armor");
    public static final TagKey<Item> SKULLS = tag("minecraft", "skulls");
    public static final TagKey<Item> TRIMMABLE_ARMOR = tag("minecraft", "trimmable_armor");
    public static final TagKey<Item> TRIM_MATERIALS = tag("minecraft", "trim_materials");
    public static final TagKey<Item> TRIM_TEMPLATES = tag("minecraft", "trim_templates");
    public static final TagKey<Item> DECORATED_POT_SHERDS = tag("minecraft", "decorated_pot_sherds");
    public static final TagKey<Item> DECORATED_POT_INGREDIENTS = tag("minecraft", "decorated_pot_ingredients");
    public static final TagKey<Item> SWORDS = tag("minecraft", "swords");
    public static final TagKey<Item> AXES = tag("minecraft", "axes");
    public static final TagKey<Item> HOES = tag("minecraft", "hoes");
    public static final TagKey<Item> PICKAXES = tag("minecraft", "pickaxes");
    public static final TagKey<Item> SHOVELS = tag("minecraft", "shovels");
    public static final TagKey<Item> BREAKS_DECORATED_POTS = tag("minecraft", "breaks_decorated_pots");
    public static final TagKey<Item> VILLAGER_PLANTABLE_SEEDS = tag("minecraft", "villager_plantable_seeds");
    public static final TagKey<Item> DYEABLE = tag("minecraft", "dyeable");
    public static final TagKey<Item> FOOT_ARMOR_ENCHANTABLE = tag("minecraft", "enchantable/foot_armor");
    public static final TagKey<Item> LEG_ARMOR_ENCHANTABLE = tag("minecraft", "enchantable/leg_armor");
    public static final TagKey<Item> CHEST_ARMOR_ENCHANTABLE = tag("minecraft", "enchantable/chest_armor");
    public static final TagKey<Item> HEAD_ARMOR_ENCHANTABLE = tag("minecraft", "enchantable/head_armor");
    public static final TagKey<Item> ARMOR_ENCHANTABLE = tag("minecraft", "enchantable/armor");
    public static final TagKey<Item> SWORD_ENCHANTABLE = tag("minecraft", "enchantable/sword");
    public static final TagKey<Item> FIRE_ASPECT_ENCHANTABLE = tag("minecraft", "enchantable/fire_aspect");
    public static final TagKey<Item> SHARP_WEAPON_ENCHANTABLE = tag("minecraft", "enchantable/sharp_weapon");
    public static final TagKey<Item> WEAPON_ENCHANTABLE = tag("minecraft", "enchantable/weapon");
    public static final TagKey<Item> MINING_ENCHANTABLE = tag("minecraft", "enchantable/mining");
    public static final TagKey<Item> MINING_LOOT_ENCHANTABLE = tag("minecraft", "enchantable/mining_loot");
    public static final TagKey<Item> FISHING_ENCHANTABLE = tag("minecraft", "enchantable/fishing");
    public static final TagKey<Item> TRIDENT_ENCHANTABLE = tag("minecraft", "enchantable/trident");
    public static final TagKey<Item> DURABILITY_ENCHANTABLE = tag("minecraft", "enchantable/durability");
    public static final TagKey<Item> BOW_ENCHANTABLE = tag("minecraft", "enchantable/bow");
    public static final TagKey<Item> EQUIPPABLE_ENCHANTABLE = tag("minecraft", "enchantable/equippable");
    public static final TagKey<Item> CROSSBOW_ENCHANTABLE = tag("minecraft", "enchantable/crossbow");
    public static final TagKey<Item> VANISHING_ENCHANTABLE = tag("minecraft", "enchantable/vanishing");
    public static final TagKey<Item> MACE_ENCHANTABLE = tag("minecraft", "enchantable/mace");
}
